# Generated by Django 3.1.7 on 2022-12-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=15, verbose_name='method')),
                ('url', models.CharField(max_length=100, verbose_name='url')),
                ('headers', models.CharField(max_length=100, verbose_name='headers')),
                ('bodys', models.CharField(max_length=100, verbose_name='bodys')),
                ('cookies', models.CharField(max_length=100, verbose_name='cookies')),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=24, verbose_name='用户注册')),
                ('password', models.CharField(max_length=24, verbose_name='密码')),
            ],
        ),
    ]
