# Generated by Django 3.1.7 on 2022-12-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interface',
            name='description',
            field=models.CharField(default='NULL', max_length=100, verbose_name='description'),
            preserve_default=False,
        ),
    ]
